spring:
  application:
    name: "products-spring-boot"

  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}

  flyway:
    enabled: true

server:
  port: 8081
